name: Generate Post Commit

concurrency:
  group: index-release-publisher
  cancel-in-progress: false

on:
  push:
    branches: [main]
    paths:
      - "plugins/**"

permissions:
  contents: write
  discussions: write

jobs:
  generate-index:
    uses: ./.github/workflows/generate-plugin-index.yml
    secrets: inherit
    with:
      before_sha: ${{ github.event.before }}
      after_sha: ${{ github.sha }}

  generate-discussions:
    needs: generate-index
    uses: ./.github/workflows/generate-plugin-discussions.yml
    secrets: inherit
    with:
      before_sha: ${{ github.event.before }}
      after_sha: ${{ github.sha }}
